### ISSUE TITLE
插件商店为空

### ISSUE THREAD

**Issue by Zayia** [zuoez02/siyuan-plugin-system#10]
使用的是挂件版的插件系统
点开插件商店，里面刷新不出来插件列表
![1680744582583](https://user-images.githubusercontent.com/35530837/230249957-0bbb0b74-ba07-4dff-962a-7fa4e1bab622.jpg)

**Comment by zuoez02** [comment]
方便打开开发者工具看一下“网络”标签页吗？访问插件商店会发起请求的，看看是否有失败问题

**Comment by Zayia** [comment]
> 方便打开开发者工具看一下“网络”标签页吗？访问插件商店会发起请求的，看看是否有失败问题

共4个请求，全部访问正常
![1680744788362](https://user-images.githubusercontent.com/35530837/230250368-001b724b-6fa1-4a99-9fc2-c9f7e4fcb406.jpg)

**Comment by Zayia** [comment]
![image](https://user-images.githubusercontent.com/35530837/230250837-2b171d89-a8af-4c0a-8732-e80c7f062741.png)
有错误

**Comment by zuoez02** [comment]
点一下那个错误的，看看实际错误是什么内容？

可以看一下插件系统配置页那个配置商店地址的输入框，看看是不是修改了？把提示信息里默认值写进去再试一次看看

**Comment by Zayia** [comment]
> 

商店地址就是按照提示信息修改的
![image](https://user-images.githubusercontent.com/35530837/230251372-6dfa61e1-facd-4447-9e1f-cffd160cb1c2.png)

**Comment by zuoez02** [comment]
看看控制台的输出内容

**Comment by Zayia** [comment]
`Failed to load resource: net::ERR_FAILED
VM89:2 [PluginSystem] [09:37:38] INFO plugin system : No plugin found in /data/plugins
VM89:2 [PluginSystem] [09:39:03] INFO plugin system : No plugin found in /data/plugins
gua.ee/:1 
        
       Access to XMLHttpRequest at 'https://bitbucket.org/siyuan-plugin/siyuan-plugins/raw/main//plugins.json' from origin 'http://gua.ee:6806' has been blocked by CORS policy: Request header field cache-control is not allowed by Access-Control-Allow-Headers in preflight response.
VM89:2 
        
       AxiosError
loadPluginsFromUrl @ VM89:2
bitbucket.org/siyuan-plugin/siyuan-plugins/raw/main//plugins.json:1 
        
      
        
        
      
        
      
       
        
       Failed to load resource: net::ERR_FAILED
VM89:2 [PluginSystem] [09:39:05] INFO plugin system : No plugin found in /data/plugins
gua.ee/:1 
        
       Access to XMLHttpRequest at 'https://bitbucket.org/siyuan-plugin/siyuan-plugins/raw/main//plugins.json' from origin 'http://gua.ee:6806' has been blocked by CORS policy: Request header field cache-control is not allowed by Access-Control-Allow-Headers in preflight response.
VM89:2 
        
       AxiosError
loadPluginsFromUrl @ VM89:2
bitbucket.org/siyuan-plugin/siyuan-plugins/raw/main//plugins.json:1 
        
      
        
        
      
        
      
       
        
       Failed to load resource: net::ERR_FAILED
VM89:2 [PluginSystem] [09:41:21] INFO plugin system : No plugin found in /data/plugins
gua.ee/:1 
        
       Access to XMLHttpRequest at 'https://bitbucket.org/siyuan-plugin/siyuan-plugins/raw/main//plugins.json' from origin 'http://gua.ee:6806' has been blocked by CORS policy: Request header field cache-control is not allowed by Access-Control-Allow-Headers in preflight response.
VM89:2 
        
       AxiosError {message: 'Network Error', name: 'AxiosError', code: 'ERR_NETWORK', config: {…}, request: XMLHttpRequest, …}
loadPluginsFromUrl @ VM89:2
await in loadPluginsFromUrl(异步)
init @ VM89:2
loadPlugins @ VM89:2
eval @ VM89:2
run @ VM89:2
eval @ VM89:2
flush @ VM89:2
Promise.then(异步)
schedule_update @ VM89:2
make_dirty @ VM89:2
eval @ VM89:2
i @ VM89:2
eval @ VM89:2
p @ VM89:2
VM89:2 
        
      
        
        
      
        
      
       
        
       GET https://bitbucket.org/siyuan-plugin/siyuan-plugins/raw/main//plugins.json net::ERR_FAILED
eval @ VM89:2
xhr @ VM89:2
dispatchRequest @ VM89:2
request @ VM89:2
utils.forEach.Axios.<computed> @ VM89:2
eval @ VM89:2
loadPluginsFromUrl @ VM89:2
init @ VM89:2
loadPlugins @ VM89:2
eval @ VM89:2
run @ VM89:2
eval @ VM89:2
flush @ VM89:2
Promise.then(异步)
schedule_update @ VM89:2
make_dirty @ VM89:2
eval @ VM89:2
i @ VM89:2
eval @ VM89:2
p @ VM89:2
VM89:2 [PluginSystem] [09:44:18] INFO plugin system : No plugin found in /data/plugins`

**Comment by zuoez02** [comment]
哦，我知道为啥了，你是docker版本吧？现在还有跨域的问题，还需要一些时间解决的

**Comment by Zayia** [comment]
> 

好吧。。。

**Comment by zuoez02** [comment]
web端现在支持很差，基本上还不可用，后面有时间尝试修复。这块受限比较多，一个是请求这块，另外现在托管的服务器也不支持跨域，
