### ISSUE TITLE
能否直接在插件管理中，直接看到代码片段

### ISSUE THREAD

**Issue by MXDMM** [zuoez02/siyuan-plugin-system#16]
能否直接在插件管理中，直接看到代码片段，然后进行修改代码呢？然后类型转为个人特殊代码（不对外公开）。

这样可能易用性更高一些（想对于查找“代码片段”），也能够直接参考别人的代码，学习之后更容易去写一些简单易用的代码片段。

说实话，我也是接触了这个插件，才察觉到“代码片段”的好处，但是本身不会写JS，十分想参考学习，同时有些功能自己也想做调整。

**Comment by zuoez02** [comment]
插件很多都是编译后的，无法直接进行修改。如果有需要的话，可以在本地直接打开对应插件的文件进行修改，就不在插件系统里实现这么复杂的功能了。
