### ISSUE TITLE
请问这个和siyuan-plugin-system-widget是不是可以合并？

### ISSUE THREAD

**Issue by AugustTuan** [zuoez02/siyuan-plugin-system#8]
[zuoez02/siyuan-plugin-system-widget: Siyuan Plugin System installer widget](https://github.com/zuoez02/siyuan-plugin-system-widget)

挂件的使用问题，一般就是插件面板的问题，感觉可以合并到这个仓库🤣

**Comment by zuoez02** [comment]
这个是插件的仓库，跟插件系统是两个东西
