### ISSUE TITLE
为什么 lsNotebooks API 需要一个 sql 参数？

### ISSUE THREAD

**Issue by frostime** [zuoez02/siyuan-plugin-system#9]
当前的 lsnotebooks api接受一个 sql 参数。

```ts
export async function lsNotebooks(sql) {
    let sqldata = { stmt: sql };
    let url = '/api/notebook/lsNotebooks';
    return parseBody(request(url, sqldata));
}
```

但是我翻了一下思源的 [api档案](https://github.com/siyuan-note/siyuan/blob/master/API.md#List-notebooks) 并没有这个要求。
![image](https://user-images.githubusercontent.com/27268127/230032899-814a5011-f45e-4d7b-8efd-a9ab65df1356.png)

虽然在使用的时候直接传入 "" 也不影响操作，但我还是好奇这个 sql 参数是干什么用的。

**Comment by zuoez02** [comment]
这些是其他开发者提供的，我并没有验证，估计是遗留问题吧
